appName: Notepad
comboKey: shift
playerClass: Soulbeast PvP
showHUD: '0'
skill01: '1'
skill02: '2'
skill03: '3'
skill04: '4'
skill05: '5'
skill06: r
skill07: z
skill08: x
skill09: c
skill10: e
stompKey: f
weaponSwap: q
